### PR TITLE
Update to allow connections to new CFMM DICOM server

### PR DESCRIPTION
**Pull request by isolovey**
This version will allow to switch between old (dcm4chee v2) and new (dcm4chee v5) DICOM server. This can be done with Docker ENVs or command-line options.

Old server is reachable at `CFMM-Public@dicom.cfmm.uwo.ca:11112`. TLS options are `--tls11 --tls-cipher=TLS_RSA_WITH_AES_128_CBC_SHA`.

New server is reachable at `CFMM-Public@dicom.cfmm.uwo.ca:11115`. TLS options are `--tls-aes`.

Note that I had to change port of the new server from `11122` to `11115` in order to make the server reachable from Compute Canada.

### CODE REVIEW

**Comment by akhanf** [comment]
oops just realized we never merged this -- happy to merge it in if it is ready now

**Comment by isolovey** [comment]
@akhanf This branch will work with the new CFMM DICOM server. The old server is no longer accessible via a public DICOM port.

**Comment by isolovey** [comment]
> oops just realized we never merged this -- happy to merge it in if it is ready now

All good - had to make a last minute change anyway. Ready to merge.

**Comment by akhanf** [comment]
I'm not able to get things working with the new dicom server, either from a robarts VM or compute canada. @isolovey this is how I am running it - did this work for you?

```
$ singularity run -e cfmm2tar_latest.sif -x "--tls-aes" -s CFMM-Public@dicom.cfmm.uwo.ca:11115  -d '20210818-20211120' -p 'Burneo^EpLinkPhase3' .

2021/11/20 08:54:08-ERROR-Picked up _JAVA_OPTIONS: -Xmx2048m
findscu: Connection timed out (Connection timed out)
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.dcm4che3.net.Connection.connect(Connection.java:1047)
	at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:629)
	at org.dcm4che3.tool.findscu.FindSCU.open(FindSCU.java:437)
	at org.dcm4che3.tool.findscu.FindSCU.main(FindSCU.java:352)
```

**Comment by isolovey** [comment]
The port is now reverted back to 11112 (11115 was just for testing before the final switch), and the AE Title had to be changed to `CFMM` from `CFMM-Public`. Sorry for the confusion, I should have been more clear in the MR.

Please try with `CFMM@dicom.cfmm.uwo.ca:11112`. It is the default in the `Dockerfile`, so this will work:

```bash
singularity run -e /scratch/isolovey/cfmm2tar_latest.sif  -d '20210818-20211120' -p 'Burneo^EpLinkPhase3' .
```

**Comment by akhanf** [comment]
Ah OK perfect, is working for me now.. I'll make a release tag so we can tell people to update their containers

**Pull request merged**
